EC:
  - https://www.gentex.com/
  - https://view.com/
  - https://www.sageglass.com/
  - https://chromogenics.com/
  - https://www.lannray.com/about-us/
  - https://www.ioptee.com/
  - http://www.boyu-tech.cn/
  - https://www.vdiglass.com/
  - http://www.yapuglass.com/about/?67.html
  - https://www.nbmrkj.com/
  - https://www.suntint.cn/
PDLC:
  - http://www.hiuv.net/index.html
  - http://www.lsoptronics.cn/
SPD:
  - https://www.gauzy.com/
  - https://j1ai.com/guanyuwomen/
LC:
  - https://www.global.dnp/zh-CHS/index.html
  - https://boe.com/
  - https://www.wicue.com/index.html
Others:
  - https://www.gentex.com/
  - https://view.com/
  - https://www.sageglass.com/
  - https://chromogenics.com/
  - https://www.lannray.com/about-us/
  - https://www.ioptee.com/
  - http://www.boyu-tech.cn/
  - https://www.vdiglass.com/
  - http://www.yapuglass.com/about/?67.html
  - https://www.nbmrkj.com/
  - https://www.suntint.cn/
  - http://www.hiuv.net/index.html
  - http://www.lsoptronics.cn/
  - https://www.gauzy.com/
  - https://j1ai.com/guanyuwomen/
  - https://www.global.dnp/zh-CHS/index.html
  - https://boe.com/
  - https://www.wicue.com/index.html
